name: Publish package on pypi

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  publish-flow:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 2.4.0

      - name: Install library
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest

        # publish version only when pyproject.toml is changed in master
      - name: Filter changes in pyproject
        uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            root:
              - 'pyproject.toml'

      - if: ${{ (github.ref == 'refs/heads/master') && (steps.changes.outputs.root == 'true')}}
        name: Build
        run: poetry build

      - if: ${{ (github.ref == 'refs/heads/master') && (steps.changes.outputs.root == 'true')}}
        name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
